# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkdYWG0g5lGmYpm30lfqCALCZWkwSbl3
"""

# This program asks for the user's name and available study hours,
# then recommends a study plan.

name = input("Enter your name: ")

study_hours = int(input("How many hours can you study today? "))

if study_hours >= 2:
    print(f"{name}, you have {study_hours} hours. You have enough time to study Python.")
else:
    print(f"{name}, you have {study_hours} hours. Complete a short review.")

# Example Run 1
# Inputs: Rafi, 3
# Output: Rafi, you have 3 hours. You have enough time to study Python.

# Example Run 2
# Inputs: Rafi, 0
# Output: Rafi, you have 0 hours. Complete a short review.